---
- name: "Disable updates"
  script: files/misc/disable-updates.sh

# TODO: Configure hostname here

- name: Load the user_data variable file from the playbook or from a default location (used for ansible-pull)
  include_vars: "{{ item }}"
  with_first_found:
    - "ansible_user_data.yml"
    - "/var/lib/micado/ansible_user_data.yml"

- name: 'Installing packages'
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https # TODO: Docker part will install this
    - ca-certificates # TODO: Docker part will install this
    - curl
    - software-properties-common
    - wget
    - unzip
    - jq
    - dnsmasq

# FIXME: Why do we need this?
- name: 'Create Prometheus user'
  user:
    name: prometheus
    createhome: no
    state: present

- include: docker-install.yml

- include: files.yml

- include: worker_node.yml

- include: docker-pull-images.yml

- include: submitter-setup.yml

- name: "Run runcmd.sh script #FIXME"
  script: files/misc/runcmd.sh
