---

- name: 'Installing Python3 & pip3'
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip

- name: 'Installing submitter requirements'
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - virtualenv

- name: 'Setup Virtual Environment'
  script: files/misc/build_venv.sh
