---
- name: Deploy MiCADO master
  hosts: micado
  gather_facts: False

  pre_tasks:
  - name: (Ansible) Include pre-tasks
    include_tasks: "{{ task_item }}"
    loop: "{{ query('fileglob', \"pre-task/[0-9][0-9]*.yml\")|sort }}"
    loop_control:
      loop_var: task_item
    tags:
    - always

    - name: Persist some variables
      set_fact:
        enable_occopus: "{{ enable_occopus }}"
        enable_terraform: "{{ enable_terraform }}"
        disable_worker_updates: "{{ disable_worker_updates }}"
      tags:
      - build
      - start
      - edge

  roles:
    - role: micado_master/build
      tags:
      - build
    - role: micado_master/start
      tags:
      - start

- name: Setup KubeEdge (Cloud-core)
  hosts: micado

  roles:
    - role: micado_edge/start
      tags:
      - edge

- name: Setup KubeEdge (Edge-core)
  hosts: edgenodes
  serial: 1
  gather_facts: True

  pre_tasks:
  - name: (Ansible) Include pre-tasks
    include_tasks: "{{ task_item }}"
    loop: "{{ query('fileglob', \"pre-task/[0-9][0-9]*.yml\")|sort }}"
    loop_control:
      loop_var: task_item
    tags:
    - always

  roles:
    - role: micado_edge/join
      tags:
      - edge
