---
- include: set-hostname.yml

- include: add-public-ip.yml
  when: |-
    advertise_public|default(False)
    and ansible_default_ipv4.address != ansible_host

- name: '(systemd) Collect systemd service facts'
  service_facts:
  register: services

- include: kubernetes-join.yml
  when: ansible_facts.services['kubelet.service']['state'] != "running"